package com.infosys.smartshelfx.repository;

import com.infosys.smartshelfx.entity.PurchaseOrder;
import com.infosys.smartshelfx.entity.PurchaseOrderStatus;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

@Repository
public interface PurchaseOrderRepository extends JpaRepository<PurchaseOrder, Long> {

    Optional<PurchaseOrder> findByPoNumber(String poNumber);

    boolean existsByPoNumber(String poNumber);

    Page<PurchaseOrder> findByVendorId(Long vendorId, Pageable pageable);

    Page<PurchaseOrder> findByStatus(PurchaseOrderStatus status, Pageable pageable);

    List<PurchaseOrder> findByStatusIn(List<PurchaseOrderStatus> statuses);

    @Query("SELECT po FROM PurchaseOrder po WHERE po.vendor.id = :vendorId AND po.status = :status")
    Page<PurchaseOrder> findByVendorIdAndStatus(@Param("vendorId") Long vendorId,
            @Param("status") PurchaseOrderStatus status, Pageable pageable);

    @Query("SELECT po FROM PurchaseOrder po WHERE " +
            "(:vendorId IS NULL OR po.vendor.id = :vendorId) AND " +
            "(:status IS NULL OR po.status = :status) AND " +
            "(:startDate IS NULL OR po.createdAt >= :startDate) AND " +
            "(:endDate IS NULL OR po.createdAt <= :endDate)")
    Page<PurchaseOrder> findWithFilters(
            @Param("vendorId") Long vendorId,
            @Param("status") PurchaseOrderStatus status,
            @Param("startDate") LocalDateTime startDate,
            @Param("endDate") LocalDateTime endDate,
            Pageable pageable);

    @Query("SELECT COUNT(po) FROM PurchaseOrder po WHERE po.status = :status")
    Long countByStatus(@Param("status") PurchaseOrderStatus status);

    @Query("SELECT po FROM PurchaseOrder po WHERE po.isAutoGenerated = true AND po.status = 'PENDING'")
    List<PurchaseOrder> findPendingAutoGeneratedOrders();

    @Query("SELECT po FROM PurchaseOrder po WHERE po.createdAt BETWEEN :startDate AND :endDate")
    List<PurchaseOrder> findByDateRange(@Param("startDate") LocalDateTime startDate,
            @Param("endDate") LocalDateTime endDate);

    @Query("SELECT SUM(po.grandTotal) FROM PurchaseOrder po WHERE po.status IN :statuses AND " +
            "po.createdAt BETWEEN :startDate AND :endDate")
    java.math.BigDecimal getTotalPurchaseAmount(
            @Param("statuses") List<PurchaseOrderStatus> statuses,
            @Param("startDate") LocalDateTime startDate,
            @Param("endDate") LocalDateTime endDate);

    List<PurchaseOrder> findByVendorIdAndCreatedAtBetween(Long vendorId, LocalDateTime startDate,
            LocalDateTime endDate);

    @Query("SELECT po FROM PurchaseOrder po WHERE po.status = :status ORDER BY po.createdAt DESC")
    List<PurchaseOrder> findByStatusOrderByCreatedAtDesc(@Param("status") PurchaseOrderStatus status);

    List<PurchaseOrder> findByCreatedAtBetween(LocalDateTime startDate, LocalDateTime endDate);
}
