package com.infosys.smartshelfx.entity;

public enum NotificationType {
    LOW_STOCK_ALERT,
    OUT_OF_STOCK_ALERT,
    EXPIRY_ALERT,
    EXPIRY_WARNING,
    RESTOCK_SUGGESTION,
    REORDER_SUGGESTION,
    PURCHASE_ORDER_CREATED,
    PURCHASE_ORDER_APPROVED,
    PURCHASE_ORDER_REJECTED,
    PURCHASE_ORDER_RECEIVED,
    STOCK_RECEIVED,
    STOCK_DISPATCHED,
    VENDOR_RESPONSE,
    SYSTEM_ALERT,
    FORECAST_ALERT
}
